/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculatortrail;

/**
 *
 * @author ASUS
 */
public class CalculatorUI extends javax.swing.JFrame {

    /**
     * Creates new form CalculatorUI
     */
    protected double firstValue;
    protected double secondValue;
    protected double result;
    protected String operator;
    
    public CalculatorUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtOutput = new javax.swing.JTextField();
        jbtnBackspace = new javax.swing.JButton();
        jbtnAllClear = new javax.swing.JButton();
        jbtnDivide = new javax.swing.JButton();
        jbtnClear = new javax.swing.JButton();
        jbtnEight = new javax.swing.JButton();
        jbtnSeven = new javax.swing.JButton();
        jbtnMultiple = new javax.swing.JButton();
        jbtnNine = new javax.swing.JButton();
        jbtnFive = new javax.swing.JButton();
        jbtnFour = new javax.swing.JButton();
        jbtnSubstration = new javax.swing.JButton();
        jbtnSix = new javax.swing.JButton();
        jbtnTwo = new javax.swing.JButton();
        jbtnOne = new javax.swing.JButton();
        jbtnAdd = new javax.swing.JButton();
        jbtnThree = new javax.swing.JButton();
        jbtnZero = new javax.swing.JButton();
        jbtnPM = new javax.swing.JButton();
        jbtnEquals = new javax.swing.JButton();
        jbtnDot = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtOutput.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jtxtOutput.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtOutputActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 350, 50));

        jbtnBackspace.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnBackspace.setText("←");
        jbtnBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackspaceActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBackspace, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 80, 60));

        jbtnAllClear.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnAllClear.setText("AC");
        jbtnAllClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAllClearActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnAllClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 80, 60));

        jbtnDivide.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnDivide.setText("÷");
        jbtnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDivideActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDivide, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 80, 60));

        jbtnClear.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnClear.setText("C");
        jbtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClearActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 80, 60));

        jbtnEight.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnEight.setText("8");
        jbtnEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEightActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnEight, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 80, 60));

        jbtnSeven.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnSeven.setText("7");
        jbtnSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSevenActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnSeven, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 80, 60));

        jbtnMultiple.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnMultiple.setText("x");
        jbtnMultiple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMultipleActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnMultiple, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 80, 60));

        jbtnNine.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnNine.setText("9");
        jbtnNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNineActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnNine, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 80, 60));

        jbtnFive.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnFive.setText("5");
        jbtnFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFiveActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnFive, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 80, 60));

        jbtnFour.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnFour.setText("4");
        jbtnFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFourActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnFour, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 80, 60));

        jbtnSubstration.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnSubstration.setText("-");
        jbtnSubstration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSubstrationActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnSubstration, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 80, 60));

        jbtnSix.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnSix.setText("6");
        jbtnSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSixActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnSix, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 80, 60));

        jbtnTwo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnTwo.setText("2");
        jbtnTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTwoActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 80, 60));

        jbtnOne.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnOne.setText("1");
        jbtnOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOneActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 80, 60));

        jbtnAdd.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnAdd.setText("+");
        jbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 80, 60));

        jbtnThree.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnThree.setText("3");
        jbtnThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnThreeActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnThree, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 80, 60));

        jbtnZero.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnZero.setText("0");
        jbtnZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnZeroActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnZero, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 80, 60));

        jbtnPM.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnPM.setText("+/-");
        jbtnPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPMActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 80, 60));

        jbtnEquals.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnEquals.setText("=");
        jbtnEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEqualsActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnEquals, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 80, 60));

        jbtnDot.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnDot.setText(".");
        jbtnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDotActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 80, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void enterNumber (String value)
    {
       String nums = jtxtOutput.getText() + value;
       jtxtOutput.setText(nums);
    }
  
    private void jtxtOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtOutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtOutputActionPerformed

    private void jbtnAllClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAllClearActionPerformed
        jtxtOutput.setText("");

        String firstNumber, secondNumber;   
        
        firstNumber = String.valueOf(firstValue);
        secondNumber = String.valueOf(secondValue);
        
        firstNumber = "";
        secondNumber = "";
    }//GEN-LAST:event_jbtnAllClearActionPerformed

    private void jbtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClearActionPerformed
        jtxtOutput.setText("");
    }//GEN-LAST:event_jbtnClearActionPerformed

    private void jbtnEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEightActionPerformed
        enterNumber("8");
    }//GEN-LAST:event_jbtnEightActionPerformed

    private void jbtnSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSevenActionPerformed
        enterNumber("7");
    }//GEN-LAST:event_jbtnSevenActionPerformed

    private void jbtnNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNineActionPerformed
        enterNumber("9");
    }//GEN-LAST:event_jbtnNineActionPerformed

    private void jbtnFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFiveActionPerformed
        enterNumber("5");
    }//GEN-LAST:event_jbtnFiveActionPerformed

    private void jbtnFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFourActionPerformed
        enterNumber("4");
    }//GEN-LAST:event_jbtnFourActionPerformed

    private void jbtnSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSixActionPerformed
        enterNumber("6");
    }//GEN-LAST:event_jbtnSixActionPerformed

    private void jbtnTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTwoActionPerformed
        enterNumber("2");
    }//GEN-LAST:event_jbtnTwoActionPerformed

    private void jbtnOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOneActionPerformed
        enterNumber("1");
    }//GEN-LAST:event_jbtnOneActionPerformed

    private void jbtnThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnThreeActionPerformed
        enterNumber("3");
    }//GEN-LAST:event_jbtnThreeActionPerformed

    private void jbtnZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnZeroActionPerformed
        enterNumber("0");
    }//GEN-LAST:event_jbtnZeroActionPerformed

    private void jbtnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDivideActionPerformed
        firstValue = Double.parseDouble(jtxtOutput.getText());
        jtxtOutput.setText("");
        operator = "/";
    }//GEN-LAST:event_jbtnDivideActionPerformed

    private void jbtnMultipleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMultipleActionPerformed
        firstValue = Double.parseDouble(jtxtOutput.getText());
        jtxtOutput.setText("");
        operator = "*";
    }//GEN-LAST:event_jbtnMultipleActionPerformed

    private void jbtnSubstrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSubstrationActionPerformed
        firstValue = Double.parseDouble(jtxtOutput.getText());
        jtxtOutput.setText("");
        operator = "-";
    }//GEN-LAST:event_jbtnSubstrationActionPerformed

    private void jbtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddActionPerformed
       firstValue = Double.parseDouble(jtxtOutput.getText());
       jtxtOutput.setText("");
       operator = "+";
    }//GEN-LAST:event_jbtnAddActionPerformed

    private void jbtnPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPMActionPerformed
        double numbers = Double.parseDouble(String.valueOf(jtxtOutput.getText()));
        numbers = numbers * (-1);
        jtxtOutput.setText(String.valueOf(numbers));
    }//GEN-LAST:event_jbtnPMActionPerformed

    private void jbtnBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackspaceActionPerformed
        String backspace = null;
        
        if (jtxtOutput.getText().length() > 0){
            StringBuilder sb = new StringBuilder(jtxtOutput.getText());
            sb.deleteCharAt(jtxtOutput.getText().length() - 1);
            backspace = sb.toString();
            jtxtOutput.setText(backspace);
        }
    }//GEN-LAST:event_jbtnBackspaceActionPerformed

    private void jbtnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDotActionPerformed
        if(!jtxtOutput.getText().contains(".")){
           jtxtOutput.setText(jtxtOutput.getText() + jbtnDot.getText());
        }
        
    }//GEN-LAST:event_jbtnDotActionPerformed

    private void jbtnEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEqualsActionPerformed
        secondValue = Double.parseDouble(jtxtOutput.getText());
        
        if(operator == "+"){
            result = firstValue + secondValue;
            jtxtOutput.setText(String.valueOf(result));
        }else if(operator == "-"){
            result = firstValue - secondValue;
            jtxtOutput.setText(String.valueOf(result));
        }else if(operator == "*"){
            result = firstValue * secondValue;
            jtxtOutput.setText(String.valueOf(result));
        }else if(operator == "/"){
            result = firstValue / secondValue;
            jtxtOutput.setText(String.valueOf(result));
        }
    }//GEN-LAST:event_jbtnEqualsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnAdd;
    private javax.swing.JButton jbtnAllClear;
    private javax.swing.JButton jbtnBackspace;
    private javax.swing.JButton jbtnClear;
    private javax.swing.JButton jbtnDivide;
    private javax.swing.JButton jbtnDot;
    private javax.swing.JButton jbtnEight;
    private javax.swing.JButton jbtnEquals;
    private javax.swing.JButton jbtnFive;
    private javax.swing.JButton jbtnFour;
    private javax.swing.JButton jbtnMultiple;
    private javax.swing.JButton jbtnNine;
    private javax.swing.JButton jbtnOne;
    private javax.swing.JButton jbtnPM;
    private javax.swing.JButton jbtnSeven;
    private javax.swing.JButton jbtnSix;
    private javax.swing.JButton jbtnSubstration;
    private javax.swing.JButton jbtnThree;
    private javax.swing.JButton jbtnTwo;
    private javax.swing.JButton jbtnZero;
    private javax.swing.JTextField jtxtOutput;
    // End of variables declaration//GEN-END:variables
}
